sudo: required

language: python

python:
  - "3.6"

cache: pip

install:
  - pip install pipenv
  - pipenv install --dev

script:
  - pytest -m fast

branches:
  only:
  - master
  - dev

notifications:
  email: false
